apiVersion: v1
kind: PersistentVolume
metadata:
  name: azure-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  azureFile:
    secretName: azure-secret
    shareName: msi-fshare
    readOnly: false
  mountOptions:
  - dir_mode=0751
  - file_mode=0751
  - uid=999
  - gid=999
  - mfsymlinks
  - nobrl
