apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-azure-claim-3
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "standard"
  resources:
    requests:
      storage: 5Gi