name: "TestPush "
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_push_app:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v1

      - name: Repo lowecase
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
        
      - name: Check file existence app
        id: check_files
        uses: andstor/file-existence-action@v1
        working-directory: app_docker_env
        with:
          files: "Dockerfile"

      - name: File exists app
        if: steps.build_push.outputs.files_exists == 'true'
        uses: docker/build-push-action@v1
        working-directory: app_docker_env
        with:
          username: dsecid
          password: ${{ secrets.REGISTRY_TOKEN }}
          registry: ghcr.io
          repository: ${{ env.REPO }}
          tag_with_ref: true
          name: 'Buraz'

  build_push_db:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: database_app_docker
    steps:
      - name: Repo lowecase
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
          
      - name: Checkout repo
        uses: actions/checkout@v1


      - name: Check file existence app
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "Dockerfile"

      - name: File exists db
        if: steps.build_push.outputs.files_exists == 'true'
        uses: docker/build-push-action@v1
        with:
          username: dsecid
          password: ${{ secrets.REGISTRY_TOKEN }}
          registry: ghcr.io
          repository: ${{ env.REPO }}
          tag_with_ref: true
          name: 'Buraz'
