name: "TestPush "
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_push_app:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v1

      - name: Repo lowecase
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
        
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Build image and push to Docker Hub and GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./app_docker_env
          # Note: tags has to be all lower-case
          tags: dsecid/msi_app:latest
          push: true
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
